### ISSUE TITLE
想问一下您能否提供一份 c# 的代码示例吗？

### ISSUE THREAD

**Issue by Gaoyifei1011** [Blinue/XamlIslandsCpp#1]
想问一下您能否提供一份 c# 的代码示例吗？

昨天我偶然发现了您提供的包含自定义标题栏的 XAML Islands C++ 示例代码，尝试将其转换为 C# 版本时遇到了一些困难。因此，想请教您是否能够提供一份 C# 版本的代码？

![51edf0594e0f0407374723b38dad3884](https://github.com/user-attachments/assets/506b7764-84ab-4a85-9bac-08a83d063c5d)
[XamlIslandsCSharp.zip](https://github.com/user-attachments/files/17932428/XamlIslandsCSharp.zip)

**Comment by Blinue** [comment]
移植成 C# 确实相当复杂，需要海量的 P/Invoke。感谢你的移植，不过你大概不熟悉 C++，里面有不少微妙的错误，我都已经修复了。我在 Win10 上顺利运行，不过没在 Win11 上测试，可能存在没排查到的 bug。
[XamlIslandsCSharp.zip](https://github.com/user-attachments/files/17943056/XamlIslandsCSharp.zip)

此外这个 patch 包含了我做的更改
[Patch.patch](https://github.com/user-attachments/files/17943065/Patch.patch)

我个人认为这个项目移植成 C# 是吃力不讨好的行为，C++ 的优势太多了

* 运行速度更快
* 包的体积更小
* 没有外部依赖
* 不需要打包
* 可以方便的调用原生接口

不过移植成 C# 也有很大价值，我从来没在 C# 项目里看到过优秀的标题栏实现，希望你将这个项目开源，让更多人可以使用 ;)

**Comment by Gaoyifei1011** [comment]
> 移植成 C# 确实相当复杂，需要海量的 P/Invoke。感谢你的移植，不过你大概不熟悉 C++，里面有不少微妙的错误，我都已经修复了。我在 Win10 上顺利运行，不过没在 Win11 上测试，可能存在没排查到的 bug。 [XamlIslandsCSharp.zip](https://github.com/user-attachments/files/17943056/XamlIslandsCSharp.zip)
> 
> 此外这个 patch 包含了我做的更改 [Patch.patch](https://github.com/user-attachments/files/17943065/Patch.patch)
> 
> 我个人认为这个项目移植成 C# 是吃力不讨好的行为，C++ 的优势太多了
> 
> * 运行速度更快
> * 包的体积更小
> * 没有外部依赖
> * 不需要打包
> * 可以方便的调用原生接口
> 
> 不过移植成 C# 也有很大价值，我从来没在 C# 项目里看到过优秀的标题栏实现，希望你将这个项目开源，让更多人可以使用 ;)

非常感谢，正是因为涉及到大量的 P/Invoke，所以才暂时引入 CsWin32 这个库作为一个过渡跳板作为测试。如果最终效果好的话，最终我会手动 P/Invoke，尝试在 Mile.Xaml （Xaml islands 的轻量化版本）的代码例子中作为一个代码贡献示例。

正式因为没有 c# 版本优秀的开源实现（虽然 Microsoft 在 Windows App SDK 提供了一个可用的 API，但是没开源，所以不知道内部原理），所以我尝试自己实现一个并将其开源。

我的确不是很熟悉 c++，也是我的短板，这也是我以后未来继续要努力的重要方向

[Mile.Xaml](https://github.com/ProjectMile/Mile.Xaml)
[Mile.Xaml.Samples](https://github.com/ProjectMile/Mile.Xaml.Samples)

**Comment by luojunyuan** [comment]
参照 Blinue 大大的这个项目，我做了一份 csharp 版的 xaml island 库。感觉开发体验比较好，等同于 modern uwp。

Aot编译后，不带任何依赖仅有 5mb 左右，带上 Microsoft.UI.Xaml.dll，Aot 后总共才 14.2 MB。

不需要打包，可以调用 uwp 版的社区控件库。

目前还没有做好自定义标题栏等内容，只是完成了开箱即用的第一步。

https://github.com/luojunyuan/CoreIsland

cc @Blinue
